# Generated by Django 2.1 on 2018-08-23 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_interface.Customer')),
            ],
            options={
                'db_table': 'customer_items',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.AddField(
            model_name='customeritems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_interface.Item'),
        ),
    ]
