# Generated by Django 2.1 on 2018-08-23 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0002_auto_20180823_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_interface.Customer')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.RenameModel(
            old_name='CustomerItems',
            new_name='CustomerItem',
        ),
    ]
