# Generated by Django 2.1 on 2018-08-23 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0003_auto_20180823_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(default=0)),
                ('qte', models.CharField(default='', max_length=200)),
                ('active', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_interface.Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_interface.Item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_interface.Location')),
            ],
            options={
                'db_table': 'standing_orders',
            },
        ),
    ]
